/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pFiche;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javaapplication7.*;

/**
 *
 * @author CAUBET
 */
public class fEntree extends javax.swing.JFrame {

    /**
     * Creates new form fEntree
     */
    public ArrayList<Lieu> listeLieux = new ArrayList<>();
    public ArrayList<Panneau> listePanneaux = new ArrayList<>();
    public ArrayList<Batterie> listeBatteries = new ArrayList<>();
    public ArrayList<Espace> listeEspaces = new ArrayList<>();

    public fEntree() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel1.setText("CHOIX TECHNO");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/panneaux-solaires-icone.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel3.setText("Modules PV");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Globe.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel5.setText("Lieu");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BATTERIE VICTRON AGM 60AH.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel7.setText("Batteries");

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Poly", "Mono", "Amorphe" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lisbonne", "Paris", "Ouagadougou" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GEL", "AGM", "TESLA" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nord ", "Sud", "Est", "Ouest" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inclinaison 1", "Inclinaison 2", "Inclinaison 3", "Inclinaison 4" }));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Boussole.png"))); // NOI18N

        jLabel9.setText("*");

        jLabel13.setText("*");

        jLabel14.setText("*");

        jLabel15.setText("*");

        jLabel16.setText("*");

        jLabel10.setText("*");

        jLabel11.setText("*");

        jLabel17.setText("*");

        jLabel12.setText("*");

        jLabel21.setText("*");

        jLabel22.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14)))
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17)))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel16))
                                        .addGap(0, 53, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel22)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        switch (jComboBox1.getSelectedItem().toString()) {
            case "Poly":
                jLabel14.setText("Blabla Poly c la vi");
                jLabel9.setText("Surface");
                jLabel10.setText("Rendement");
                jLabel11.setText("Puissance");
                jLabel17.setText("Prix");
             
                break;
            case "Mono":
                jLabel14.setText("Blabla Mono c la vi");
                jLabel14.setText("Blabla Poly c la vi");
                jLabel9.setText("Surface");
                jLabel10.setText("Rendement");
                jLabel11.setText("Puissance");
                jLabel17.setText("Prix");
                break;
            case "Amorphe":
                jLabel14.setText("Blabla Amorphe c la vi");
                 jLabel9.setText("Surface");
                jLabel10.setText("Rendement");
                jLabel11.setText("Puissance");
                jLabel12.setText("Prix");
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new fSortie().setVisible(true);

        //mettre un while pas toutes les cases remplies rester sur la page

        // TODO add your handling code here:
        // Récupérer les valeurs de chacune des combobox
        String module = jComboBox1.getSelectedItem().toString();
        String lieu = jComboBox2.getSelectedItem().toString();
        String batterie = jComboBox3.getSelectedItem().toString();
        String orientation = jComboBox4.getSelectedItem().toString();
        String inclinaison = jComboBox5.getSelectedItem().toString();


        
        
        
        // Analyser l'entrée utilisateur pour chacune des combobox
        // Selon le résultat, trouver l'obJET jAVA correspondant
        Lieu lieuEntre = getLieuParNom(lieu);
        // faire pareil pour Batterie & Panneau
        Batterie batterieEntree = getBatterieParNom(batterie);
        Panneau panneauEntree = getPanneauParNom(module);
        Espace maizEntree = listeEspaces.get(1);//????????????????????
        
       // puis appeler la fonction mathématique :
        double consotot;
        consotot = MathOperation.consotot(listeLieux);//param : Espace.consohh
        double coefperte;
        coefperte=MathOperation.coefperte(maizEntree);//param : espace maiz
        double energieprodpan;
        energieprodpan=MathOperation.energy_prod(panneauEntree, lieuEntre, maizEntree);//pan li maiz
        double surfacelibre;
        surfacelibre=MathOperation.surface_installee_libre(consotot, energieprodpan, panneauEntree);
        double surface;
        surface=MathOperation.surface_installee(maizEntree, panneauEntree); //null=maiz
        if (surfacelibre < maizEntree.getSurfacedispo()){ //pour ne pas surdim
            surface = surfacelibre;
        }
        else {
    }
       // panneauEntree.arrayprod=MathOperation.prodhh              calcul prodhh
        
        double prodtot;
        prodtot=MathOperation.prodtot(listeLieux); 
        
        ArrayList consostock ;
        
        //consostock=MathOperation.consostock( consohh,prodhh);
        
        int nbbat;
        nbbat=MathOperation.nbBat(prodtot, batterieEntree);
        double gainEnv;
        gainEnv=MathOperation.GainEnv(prodtot);
        double gainkwh;
        gainkwh=MathOperation.calculerGain(prodtot);
        double tarifbat;
        tarifbat=MathOperation.tarif(nbbat, batterieEntree);
        double autoprod;
        autoprod = MathOperation.Autoprod(prodtot, consotot);
        double autoconso;
        autoconso=1;
        
        
        
        // calculerResultat(lieuEntre, batterieEntree, panneauEntre, int inclination, int nord);
        
        //MathOperation calcul = new MathOperation();
        //calcul.calculerGain(lieuEntre, panneauEntree);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
         switch (jComboBox2.getSelectedItem().toString()) {
            case "Paris":
                jLabel15.setText("Blabla Paris c la vi");
                break;
            case "Lisbonne":
                jLabel15.setText("Blabla Lisbonne c la vi");
                break;
            
        }// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
 switch (jComboBox3.getSelectedItem().toString()) {
            case "GEL":
                jLabel16.setText("Blabla GEL c la vi");
                 jLabel12.setText("Capa");
                jLabel13.setText("Voltage");
                jLabel21.setText("Nb cycles");
                jLabel22.setText("Prix");
                break;
            case "AGM":
                jLabel16.setText("Blabla AGM c la vi");
                 jLabel12.setText("Capa");
                jLabel13.setText("Voltage");
                jLabel21.setText("Nb cycles");
                jLabel22.setText("Prix");
                break;
            case "TESLA":
                jLabel16.setText("Blabla TESLA c la vi");
                 jLabel12.setText("Capa");
                jLabel13.setText("Voltage");
                jLabel21.setText("Nb cycles");
                jLabel22.setText("Prix");
                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    public void initialiserVariables() {
        // Code ci-dessous : à répéter pour chacun des lieux à ajouter
        ArrayList<ArrayList> listeIrrh = CsvReader.main("Irrh.csv");
        Lieu tempLieu = new Lieu(147, "lisbonne", 30, 40, null);
        tempLieu.setIrrh(listeIrrh);
        listeLieux.add(tempLieu);
        // idem pour les batteries et les panneaux (créer le constructeur de Panneau et Batterie s'il existe pas)
  
        // Code ci-dessous : à répéter pour chacun des Panneaux à ajouter
        
        
        Panneau tempPan = new Panneau(1.68,15.5,260,239,null,"Poly");
        listePanneaux.add(tempPan);
        
        Panneau tempPan2 = new Panneau(1.61,17.1,280,268,null,"Mono");
        listePanneaux.add(tempPan);
        
        
        Panneau tempPan3 = new Panneau(0.79,8,50,45,null,"Amorphe");
        listePanneaux.add(tempPan);
        
         // Code ci-dessous : à répéter pour chacun des Batteries à ajouter
        Batterie tempBat = new Batterie(20,350,5000,2700,"TESLA");
        listeBatteries.add(tempBat);
        
        Batterie tempBat2 = new Batterie(230,12,600,527,"AGM");
        listeBatteries.add(tempBat);
        
        Batterie tempBat3 = new Batterie(220,12,2500,549,"GEL");
        listeBatteries.add(tempBat);
        
              
         // Code ci-dessous : à répéter pour chacun des espace à ajouter
        ArrayList<ArrayList> listeConso = CsvReader.main("consoh.csv");
        Espace tempEsp = new Espace(1,2.0,3.0,4,null);
        listeEspaces.add(tempEsp);

        
        
    }

    public Lieu getLieuParNom(String nom) {
        Iterator<Lieu> it = listeLieux.iterator();

        while (it.hasNext()) {
            Lieu tempo = it.next();
            if (tempo.getNom().equals(nom)) {
                return tempo;
            }
        }

        return null;
    }
    
      public Batterie getBatterieParNom(String nom) {
        Iterator<Batterie> it = listeBatteries.iterator();

        while (it.hasNext()) {
            Batterie tempo = it.next();
            if (tempo.getNom().equals(nom)) {
                return tempo;
            }
        }

        return null;
    }
      
      
        public Panneau getPanneauParNom(String nom) {
        Iterator<Panneau> it = listePanneaux.iterator();

        while (it.hasNext()) {
            Panneau tempo = it.next();
            if (tempo.getNom().equals(nom)) {
                return tempo;
            }
        }

        return null;
    }
    // faire getBatterieParNom
    // faire getPanneauParNom

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fEntree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fEntree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fEntree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fEntree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new fEntree().setVisible(true);
                // initialiserVariables();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
